name: Deploy To GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub Repository
        uses: actions/checkout@v3
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy to GitPages
        uses: actions/deploy-pages@v4